name: dotnet-build-package
  
on:

  workflow_dispatch:  

  workflow_call:
    inputs:
      dotnet-version:
        required: false
        type: string
        default: '8.0x'
jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup dotnet
  #       uses: actions/setup-dotnet@v4
  #       with:
  #         dotnet-version: '${{ inputs.dotnet-version }}'
  
  #     - name: Install dependencies
  #       run: dotnet restore
  
  #     - name: Build
  #       run: dotnet build --no-restore
  
  #     - name: Test with the dotnet CLI
  #       run: dotnet test --no-build

  containerize:
    
    permissions:
      contents: read
      packages: write
      # attestations: write
      # id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: ls -al -R ${{ github.workspace }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}